# Generated by Django 5.2.5 on 2025-10-02 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RawMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('stock_quantity', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('expiration_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bussiness_name', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('trade_terms', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('min_stock', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('max_stock', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('current_stock', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='Products.category')),
            ],
        ),
        migrations.CreateModel(
            name='RawSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_raw_material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='raw_materials', to='Products.rawmaterial')),
                ('fk_supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='raw_suppliers', to='Products.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='PriceHistories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('fk_raw_supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='price_histories', to='Products.rawsupplier')),
            ],
        ),
    ]
