# Generated by Django 5.2.5 on 2025-10-10 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0005_alter_product_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawsupplier',
            name='fk_raw_material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='raw_materials', to='Products.rawmaterial'),
        ),
    ]
