# Generated by Django 5.2.5 on 2025-10-10 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0006_alter_rawsupplier_fk_raw_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricehistories',
            name='fk_raw_supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='price_histories', to='Products.rawsupplier'),
        ),
    ]
