# Generated by Django 5.2.5 on 2025-10-13 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0007_alter_pricehistories_fk_raw_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmaterial',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
