# Generated by Django 5.2.5 on 2025-10-17 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0009_purchaseorder_purchaseorderdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawmaterial',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
