# Generated by Django 5.2.5 on 2025-10-17 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0010_alter_rawmaterial_expiration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='batch_control',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='batch',
            name='perishable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='batch',
            name='serie_control',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pricehistories',
            name='iva',
            field=models.DecimalField(decimal_places=2, default=1.19, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='conversor_factor',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='product',
            name='uom_sells',
            field=models.CharField(choices=[('KG', 'Kilogramos'), ('UN', 'Unidades'), ('GR', 'Gramos')], default='UN', max_length=100),
        ),
        migrations.AddField(
            model_name='supplier',
            name='country',
            field=models.CharField(blank=True, default='Chile', max_length=100),
        ),
        migrations.AddField(
            model_name='supplier',
            name='currency',
            field=models.CharField(blank=True, default='CLP', max_length=100),
        ),
        migrations.AddField(
            model_name='supplier',
            name='status',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=20),
        ),
    ]
