# Generated by Django 5.2.5 on 2025-10-17 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0011_batch_batch_control_batch_perishable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Products.product'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='raw_material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Products.rawmaterial'),
        ),
    ]
