# Generated by Django 5.2.7 on 2025-10-16 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
        ('Products', '0009_purchaseorder_purchaseorderdetail'),
        ('Sells', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batch_price_histories', to='Products.batch')),
            ],
        ),
        migrations.CreateModel(
            name='SaleOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('confirmation_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('P', 'Pendiente'), ('C', 'Confirmada'), ('A', 'Anulada')], default='P', max_length=20)),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_orders', to='Sells.client')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_orders', to='Accounts.profile')),
            ],
        ),
        migrations.CreateModel(
            name='SaleOrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price_histories', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_details', to='Sells.batchpricehistory')),
                ('sale_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='details', to='Sells.saleorder')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('type', models.CharField(choices=[('I', 'Ingreso'), ('S', 'Salida')], default='I', max_length=20)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bash', to='Products.batch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='Accounts.profile')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warehouse', to='Sells.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='WareClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=20)),
                ('association_date', models.DateField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client', to='Sells.client')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warehouses', to='Sells.warehouse')),
            ],
        ),
    ]
