# Generated by Django 5.2.5 on 2025-10-17 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sells', '0002_batchpricehistory_saleorder_saleorderdetail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='country',
            field=models.CharField(default='Chile', max_length=100),
        ),
    ]
